### ISSUE TITLE
Anonymous and email login & localization

### ISSUE THREAD

**Issue by vahidtakro** [laymonage/giscus#166] opened 2021-08-28 15:51 UTC
Giscus is amazing, but I can not use it.

Giscus is good when users are already registered on github, if you check github registeration process, it's a big step for those who don't even know about it, like the account verification,... so this seems to be strange for the person who want to make a fast comment, and this will make them to avoid writing comments.

I think writing comments should be done very easy , even easy for low-tech visitors, so just a name, email, ...
but I don't know how it can be possible as the comments are stored in Github Discussion (which I love the idea), it's easy to reply and modify.

I was checking more commenting system lately, for example [Remark42](https://github.com/umputun/remark42) is amazing, but hard to modify at least for me, also [Cusdis](https://cusdis.com/), which is nice and light, but there are still some bugs with it.

meanwhile, for those with multilingual sites, like me, it's not supporting Localization, which is a nice feature of course.

my idea is, maybe there can be a simple configuration created for those who want to put their data on Discussions, or those with databases, so if they select databases, they can turn on the options to let visitors to write anonymously, or through a simple login system. just an email address. or even if there can be a UI for managing the comments and users it would be great.

Thanks,

**Comment by nschonni** [comment] 2021-08-28 15:57
Duplicate of #65 and #108

**Comment by laymonage** [comment] 2021-08-28 16:13
Thanks for the suggestions @vahidtakro, and thanks for the pointers @nschonni.

> my idea is, maybe there can be a simple configuration created for those who want to put their data on Discussions, or those with databases, so if they select databases, they can turn on the options to let visitors to write anonymously, or through a simple login system. just an email address. or even if there can be a UI for managing the comments and users it would be great.

Sorry, but this is beyond the scope of this project. If anyone is up to the task and would like to know more about how giscus/GitHub Discussions API works, I'd be happy to assist. In any case, closing for now.

**Closed by laymonage** 2021-08-28 16:13 UTC
